//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TCNO { get; set; }
        public string Anahtar { get; set; }
        public string YETKİ { get; set; }
        public string MAILADRESI { get; set; }
        public string ADRES { get; set; }
        public string TELNO { get; set; }
        public Nullable<System.DateTime> RANDAVUTARIHIGUN { get; set; }
        public Nullable<System.TimeSpan> RANDAVUTARIHISAAT { get; set; }
        public int MuayeneSonucu { get; set; }
        public string Cinsiyet { get; set; }
        public string MedeniHali { get; set; }
        public string Kangrubu { get; set; }
        public string Dogumyeri { get; set; }
        public string DogumTarihi { get; set; }
        public string baba { get; set; }
        public string anne { get; set; }
        public string adresili { get; set; }
        public string adresilcesi { get; set; }
        public string uyruk { get; set; }
        public string sigorta { get; set; }
        public System.DateTime KayitlanmaTarihi { get; set; }
    }
}
